#**********************************************************
#* CATEGORY    GROUPS
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright (C) 2017  Haynie Research & Development

#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License along
#with this program; if not, write to the Free Software Foundation, Inc.,
#51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

default_view:
  view: yes
  entities:
    - group.climatefront
    - group.securitysettingsfront
    - group.MiscellaneousFront
    - group.locationswitchfront
    - group.scenesfront
    - group.weather
    - group.presence

Lights:
 name: Lights
 view: yes
 entities:
   - group.scenes
   - group.kitchenlights
   - group.livingroomlights
   - group.diningroomlights
   - group.outsidelights
   - group.upstairslights
   - group.masterbedroomlights
   - group.hudsonroomlights
   - group.wesleyroomlights

Climate:
  name: Climate
  view: yes
  entities:
    - group.upstairsclimate
    - group.downstairsclimate
    - group.climateautomation
    - group.hudsonroomclimate
    - group.wesleyroomclimate

Media:
 name: Media
 view: yes
 entities:
   - media_player.pandora
   - group.itunes
   - group.livingroomentertainment
   - group.kidstv
   - group.mediaplayers

Cameras:
  name: Cameras
  view: yes
  entities:
    - camera.wxradar
    - camera.living_room

Security:
  name: Security
  view: yes
  entities:
    - group.securitysettings
    - group.locationswitch
    - group.alllights
    - group.motionsensors
    - group.proximitysensors
    - group.firesensors

Settings:
  name: Settings
  view: yes
  entities:
    - group.misc
    - group.system
    - group.networktest
    - group.serverinfo
    - updater.updater
    - group.networkstatus
    - group.all_automations

UpstairsClimate:
  name: Upstairs Climate
  entities:
    - climate.upstairs
    - switch.hudsons_fan
    - switch.wesleys_fan
    - sensor.average_up_temp
    - sensor.upstairs_hallway_temperature
    - sensor.upstairs_hallway_humidity
    - sensor.hudsons_room_temperature
    - sensor.hudsons_room_humidity
    - sensor.wesleys_room_temperature
    - sensor.wesleys_room_humidity

DownstairsClimate:
  name: Downstairs Climate
  entities:
    - climate.downstairs
    - sensor.average_down_temp
    - sensor.kitchen_temperature
    - sensor.kitchen_humidity
    - sensor.master_bedroom_temperature
    - sensor.master_bedroom_humidity

ClimateFront:
  name: Home Climate
  entities:
    - sensor.average_home_temp
    - climate.downstairs
    - sensor.average_down_temp
    - climate.upstairs
    - sensor.average_up_temp

ServerInfo:
  name: Server Information
  entities:
    - sensor.cpu_use
    - sensor.ram_use
    - sensor.disk_use_
    - sensor.average_load_1m
    - sensor.average_load_5m
    - sensor.average_load_15m

Weather:
  - sensor.pws_weather
  - sensor.pws_temp_f
#    - sensor.pws_pressure_in
  - sensor.pws_relative_humidity
#    - sensor.pws_wind_dir
#    - sensor.pws_wind_string
  - sensor.dark_sky_cloud_coverage
  - sensor.dark_sky_hourly_summary
  - sensor.dark_sky_daily_summary

LocationSwitchFront:
  name: Location Switches
  control: hidden
  entities:
    - input_boolean.lancefirecall
    - script.find_katies_iphone
    - script.find_lances_iphone
    - script.find_hudsons_iphone

LocationSwitch:
  name: Location Switches
  control: hidden
  entities:
    - input_boolean.lancefirecall

SecuritySettingsFront:
  name: Security Settings
  entities:
    - alarm_control_panel.home_alarm
    - binary_sensor.smoke_and_co_co_detected
    - binary_sensor.smoke_and_co_smoke_detected

MiscellaneousFront:
  name: Miscellaneous
  entities:
    - input_select.rule_freq
    - script.game_timer
    - script.leaving_in_15_min

SecuritySettings:
  name: Security Settings
  entities:
    - alarm_control_panel.home_alarm
    - input_boolean.panic
    - input_boolean.sound_alarm
    - input_boolean.garage_alarm

ScenesFront:
  name: Lighting
  entities:
    - scene.movies
    - scene.outside_blue
    - scene.patriotic_front_porch
    - scene.outside_bright
    - scene.all_lights_on

Scenes:
  name: Lighting
  entities:
    - scene.movies
    - scene.tv_blue
    - scene.tv_red
    - scene.outside_blue
    - scene.dim_dining_room
    - scene.dim_kitchen
    - scene.patriotic_front_porch
    - scene.all_lights_on

MotionSensors:
  name: Motion Sensors
  entities:
    - binary_sensor.kitchen_presence
    - binary_sensor.master_bedroom_presence
    - binary_sensor.upstairs_hallway_presence
    - binary_sensor.hudsons_room_presence
    - binary_sensor.wesleys_room_presence

ProximitySensors:
  name: Proximity Sensors
  entities:
    - sensor.kitchen_proximity
    - sensor.master_bedroom_proximity
    - sensor.upstairs_hallway_proximity
    - sensor.hudsons_room_proximity
    - sensor.wesleys_room_proximity

FireSensors:
  name: Fire Sensors
  entities:
    - binary_sensor.smoke_and_co_co_detected
    - binary_sensor.smoke_and_co_smoke_detected

NetworkTest:
  name: Network
  entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload

Presence:
  name: Presence
  entities:
    - device_tracker.lances_iphone
    - device_tracker.katies_iphone
    - device_tracker.hudsons_iphone

Misc:
  name: Miscellaneous
  entities:
    - input_boolean.nighttimemode
    - input_boolean.flash_hudson_lights
    - input_boolean.flash_wesley_lights
    - input_boolean.hudson_grounded
    - input_boolean.wesley_grounded

System:
  name: System Controls
  entities:
    - script.restart_system
    - script.restart_jarvis_base
    - script.restart_jarvis_stt
    - script.restart_jarvis_tts

ClimateAutomation:
  name: Climate Automation Control
  entities:
    - input_boolean.hvacautomation
    - automation.downstairs_ac
    - automation.downstairs_heat
    - automation.upstairs_ac
    - automation.upstairs_heat

LivingRoomEntertainment:
  name: Living Room Entertainment
  entities:
    - media_player.plex_for_sony_playstation_4_0140
    - media_player.plex_for_vizio_vizio_mtk_2
    - input_select.livingroomharmony
    - input_slider.harmonyvolume
    - media_player.pandora
    - input_slider.systemvolume

KidsTv:
  name: Kids TVs
  entities:
    - switch.wesleytv
    - switch.hudsontv

MediaPlayers:
  name: Media Players
  entities:
    - media_player.plex_for_vizio_vizio_mtk
    - media_player.wesley_tv
    - media_player.hudson_tv_un40j5200
    - media_player.roku_yu005p719382
    - media_player.lance_office
    - media_player.itunes

KitchenLights:
  name: Kitchen
  entities:
    - light.kitchen
    - switch.pantry_hallway

LivingRoomLights:
  name: Living Room
  entities:
    - light.tv_backlight
    - scene.tv_blue

DiningRoomLights:
  name: Dining Room
  entities:
    - light.dining_room_1
    - light.dining_room_2
    - light.dining_room_3

OutsideLights:
  name: Outside
  entities:
    - light.front_porch_color_1
    - light.front_porch_color_2
    - light.front_porch_color_3
    - light.front_porch_left
    - light.front_porch_right
    - light.back_porch

OutsideColor:
  name: Outside
  entities:
    - light.front_porch_color_1
    - light.front_porch_color_2
    - light.front_porch_color_3
    - light.back_porch

OutsideWhite:
  name: Outside
  entities:
    - light.front_porch_left
    - light.front_porch_right

MasterBedroomLights:
  name: Master Bedroom
  entities:
    - switch.master_closet
    - switch.master_hallway
    - light.master_shower

UpstairsLights:
  name: Upstairs
  entities:
    - switch.upstairs_hallway
    - switch.upstairs_bathroom_main
    - switch.hudsons_light
    - switch.wesleys_light

AllLights:
  name: All Lights
  entities:
    - group.kitchenlights
    - group.livingroomlights
    - group.diningroomlights
    - group.outsidelights
    - group.masterbedroomlights
    - group.upstairslights

NetworkStatus:
  name: Network Status
  entities:
    - sensor.hue_bridge
    - sensor.wink_relay_upstairs_hall
    - sensor.jarvis_repeater
    - sensor.wink_relay_wesley
    - sensor.wink_relay_master_bed
    - sensor.wink_relay_hudson
    - sensor.synology_nas
    - sensor.lances_imac
    - sensor.harmony_hub_living_room
    - sensor.honeywell_thermostat_1
    - sensor.honeywell_thermostat_2
    - sensor.airport_extreme
    - sensor.airport_express
    - sensor.epson_wf3540
    - sensor.wink_hub
    - sensor.tpl_hudson_repeater
    - sensor.wink_relay_kitchen
    - sensor.play_station_3
    - sensor.play_station_4
    - sensor.living_room_tv
    - sensor.katies_laptop
    - sensor.citi_laptop
    - sensor.lances_ipad

AllFans:
  name: All Fans
  entities:
  - switch.hudsons_fan
  - switch.wesleys_fan
