#**********************************************************
#* CATEGORY    SCRIPTS
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright 2020 Haynie IPHC, LLC
#Developed by Haynie Research & Development, LLC
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.#
#You may obtain a copy of the License at
#http://www.apache.org/licenses/LICENSE-2.0
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

sound_alarm:
  sequence:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.vibratone_alarm
    - service: shell_command.alarm_sound
    - delay:
        seconds: 0.125
    - service: homeassistant.turn_off
      data:
        entity_id: switch.vibratone_alarm
    - service: script.turn_on
      data:
        entity_id: script.sound_alarm_loop

sound_alarm_loop:
  sequence:
    - delay:
        seconds: 0
    - service: script.turn_on
      data:
        entity_id: script.sound_alarm

sound_alarm_long:
  sequence:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 2
    - service: homeassistant.turn_off
      data:
        entity_id: switch.vibratone_alarm
    - service: script.turn_on
      data:
        entity_id: script.sound_alarm_loop_long

sound_alarm_loop_long:
  sequence:
    - delay:
        seconds: 1
    - service: script.turn_on
      data:
        entity_id: script.sound_alarm_long

sos_alarm:
  sequence:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 0.125
    - service: homeassistant.turn_off
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 0
    - service: homeassistant.turn_on
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 0.125
    - service: homeassistant.turn_off
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 0
    - service: homeassistant.turn_on
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 0.125
    - service: homeassistant.turn_off
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 0
    - service: homeassistant.turn_on
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 1
    - service: homeassistant.turn_off
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 0
    - service: homeassistant.turn_on
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 1
    - service: homeassistant.turn_off
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 0
    - service: homeassistant.turn_on
      data:
        entity_id: switch.vibratone_alarm
    - delay:
        seconds: 1
    - service: homeassistant.turn_off
      data:
        entity_id: switch.vibratone_alarm
    - service: script.turn_on
      data:
        entity_id: script.sos_alarm_loop

sos_alarm_loop:
  sequence:
    - delay:
        seconds: 1
    - service: script.turn_on
      data:
        entity_id: script.sos_alarm

garage_hazard:
  sequence:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.garage_warning_light
    - delay:
        seconds: 1
    - service: homeassistant.turn_off
      data:
        entity_id: switch.garage_warning_light
    - service: script.turn_on
      data:
        entity_id: script.garage_hazard_loop

garage_hazard_loop:
  sequence:
    - delay:
        seconds: 0
    - service: script.turn_on
      data:
        entity_id: script.garage_hazard

garage_alarm:
  sequence:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.garage_warning_light
    - delay:
        seconds: 0.125
    - service: homeassistant.turn_off
      data:
        entity_id: switch.garage_warning_light
    - service: script.turn_on
      data:
        entity_id: script.garage_alarm_loop

garage_alarm_loop:
  sequence:
    - delay:
        seconds: 0
    - service: script.turn_on
      data:
        entity_id: script.garage_hazard

find_katies_iphone:
  sequence:
    - service: notify.call
      data_template:
        message: "Hi there Katie, it appears you have lost your phone again."
        target:
          - +14352725103
    - service: shell_command.tts
      data_template:
        message: "I am calling Katies phone."
    - service: notify.twitter
      data_template:
        message: "It appears Katie lost her phone again, I am going to give it a call. #HomeAutomation #SmartHome"

find_lances_iphone:
  sequence:
    - service: notify.call
      data_template:
        message: "Hi there Lance, it appears you have lost your phone again."
        target:
          - +14355251418
    - service: shell_command.tts
      data_template:
        message: "I am calling Lances phone."
    - service: notify.twitter
      data_template:
        message: "It appears @MeanMrHaynie lost his phone again, I am going to give it a call. #HomeAutomation #SmartHome"

find_hudsons_iphone:
  sequence:
    - service: notify.call
      data_template:
        message: "Hi there Hudson, it appears you have lost your phone again."
        target:
          - +14357733385
    - service: shell_command.tts
      data_template:
        message: "I am calling Hudsons phone."
    - service: notify.twitter
      data_template:
        message: "It appears Hudson lost his phone again, I am going to give it a call. #HomeAutomation #SmartHome"

flash_hudson_lights:
  sequence:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.hudsons_light
    - delay:
        seconds: 0.125
    - service: homeassistant.turn_off
      data:
        entity_id: switch.hudsons_light
    - service: script.turn_on
      data:
        entity_id: script.flash_hudson_lights_loop

flash_hudson_lights_loop:
  sequence:
    - delay:
        seconds: 0
    - service: script.turn_on
      data:
        entity_id: script.flash_hudson_lights

flash_wesley_lights:
  sequence:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.wesleys_light
    - delay:
        seconds: 0.125
    - service: homeassistant.turn_off
      data:
        entity_id: switch.wesleys_light
    - service: script.turn_on
      data:
        entity_id: script.flash_wesley_lights_loop

flash_wesley_lights_loop:
  sequence:
    - delay:
        seconds: 0
    - service: script.turn_on
      data:
        entity_id: script.flash_wesley_lights

restart_system:
  alias: Reboot JARVIS System
  sequence:
    - service: shell_command.tts
      data_template:
        message: "I am going to reboot the Jarvis system now."
    - service: shell_command.restart_system

restart_jarvis_base:
  alias: Restart JARVIS AI
  sequence:
    - service: shell_command.tts
      data_template:
        message: "I am going to reboot the Jarvis artificial intelligience system."
    - service: shell_command.restart_jarvis_base

restart_jarvis_stt:
  alias: Reboot JARVIS STT
  sequence:
    - service: shell_command.tts
      data_template:
        message: "I am going to reboot the Jarvis speech to text system."
    - service: shell_command.restart_jarvis_stt

restart_jarvis_tts:
  alias: Reboot JARVIS TTS
  sequence:
    - service: shell_command.tts
      data_template:
        message: "I am going to reboot the Jarvis text to speech system."
    - service: shell_command.restart_jarvis_tts

leaving_in_15_min:
  alias: Leave in 15 Minutes
  sequence:
    - service: shell_command.tts
      data_template:
        message: "Thank you for pressing the self destruct button. This house will self destruct in exactly fifteen minutes."
    - delay:
        minutes: 5
    - service: shell_command.tts
      data_template:
        message: "Attention, attention, you have exactly ten minutes to be ready to leave. This house will self destruct in ten minutes."
    - delay:
        minutes: 5
    - service: shell_command.tts
      data_template:
        message: "Attention, attention, you have exactly five minutes to be ready to leave. This house will self destruct in five minutes. This is your last chance to push the cancellation button. Oh, I am sorry, the cancellation button is out of order."
    - delay:
        minutes: 2
    - service: shell_command.tts
      data_template:
        message: "Attention, This is Colonel Sanders in forward command. Abandon house. Abandon house. All personnel, proceed to escape pods. Close down the circus. Evacuate the zoo. Self-destruct mechanism has been activated. Abandon house."
    - delay:
        minutes: 1
    - service: shell_command.tts
      data_template:
        message: "This is your two minute warning. This house will self-destruct in exactly two minutes."
    - delay:
        minutes: 2
    - service: shell_command.tts
      data_template:
        message: "10. 9. 8. 7. 6. 5. 4. 3. 2. 1. Have a nice day."
    - service: shell_command.bomb_sound

game_timer:
  alias: Game Timer
  sequence:
    - service: shell_command.foghorn
    - service: shell_command.tts
      data_template:
        message: "The game timer has been activated, you have twenty minutes to play."
    - service: notify.twitter
      data_template:
        message: "The game timer was activated, the kids have 20 minutes to play. #HomeAutomation #SmartHome"
    - delay:
        minutes: 10
    - service: shell_command.tts
      data_template:
        message: "This is your ten minute warning, you have ten minutes of game time remaining."
    - delay:
        minutes: 5
    - service: shell_command.tts
      data_template:
        message: "This is your five minute warning, you have five minutes to wrap up your game."
    - service: notify.twitter
      data_template:
        message: "The kids only have 5 minutes left on their timer, they hate the countdown. #HomeAutomation #SmartHome"
    - delay:
        minutes: 4
    - service: shell_command.tts
      data_template:
        message: "This is your one minute warning, you have exactly one minute to finish up your game. Start saving or ending your game now."
    - service: notify.twitter
      data_template:
        message: "Only 1 more minute on the kids game timer, I hope they are saving like they were told to. #HomeAutomation #SmartHome"
    - delay:
        minutes: 1
    - service: shell_command.foghorn
    - service: shell_command.tts
      data_template:
        message: "The game timer is now up. Please exit your game immediatly, you have had exactly twenty minutes to play."
    - service: notify.twitter
      data_template:
        message: "Time is up on the game timer! I am going to turn their system off, otherwise they will play forever. #HomeAutomation #SmartHome"

living_room_tv_up:
  alias: Living Room TV Up
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeUp
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeUp
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeUp
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeUp
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeUp

living_room_tv_down:
  alias: Living Room TV Down
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeDown
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeDown
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeDown
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeDown
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: VolumeDown

living_room_tv_mute:
  alias: Living Room TV Mute
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: remote.living_room
        device: 17416035
        command: Mute

wesey_tv_automation_bypass:
  alias: Wesley TV Automation Bypass
  sequence:
    - service: homeassistant.turn_off
      entity_id: automation.wes_tv_school_night_automation
    - service: homeassistant.turn_off
      entity_id: automation.wes_tv_weekend_automation
    - service: homeassistant.turn_off
      entity_id: automation.wes_tv_school_night_shutoff
    - service: homeassistant.turn_off
      entity_id: automation.wesley_weekend_shutoff
    - service: homeassistant.turn_on
      entity_id: switch.wesleytv
    - delay:
        minutes: 45
    - service: homeassistant.turn_off
      entity_id: switch.wesleytv
    - service: homeassistant.turn_on
      entity_id: automation.wes_tv_school_night_automation
    - service: homeassistant.turn_on
      entity_id: automation.wes_tv_weekend_automation
    - service: homeassistant.turn_on
      entity_id: automation.wes_tv_school_night_shutoff
    - service: homeassistant.turn_on
      entity_id: automation.wesley_weekend_shutoff
