#**********************************************************
#* CATEGORY    SENSORS
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright 2020 Haynie IPHC, LLC
#Developed by Haynie Research & Development, LLC
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.#
#You may obtain a copy of the License at
#http://www.apache.org/licenses/LICENSE-2.0
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

- platform: template
  sensors:
    home_address:
      value_template: !secret home_address

    jarvis_greeting:
      value_template: '{% if is_state("sensor.random_4", "1") %}Pardon me{% elif is_state("sensor.random_4", "2") %}Pardon the interruption{% elif is_state("sensor.random_4", "3") %}Excusez-moi{% elif is_state("sensor.random_4", "4") %}Pardon{% else %}Excuse me{% endif %}'

    climate_downstairs_op_mode:
      value_template: '{{ states.climate.downstairs.attributes.operation_mode }}'

    climate_upstairs_op_mode:
      value_template: '{{ states.climate.upstairs.attributes.operation_mode }}'

    climate_downstairs_temp:
      value_template: '{{ states.climate.downstairs.attributes.current_temperature }}'

    climate_upstairs_temp:
      value_template: '{{ states.climate.upstairs.attributes.current_temperature }}'

    climate_downstairs_temp_set:
      value_template: '{{ states.climate.downstairs.attributes.temperature }}'

    climate_upstairs_temp_set:
      value_template: '{{ states.climate.upstairs.attributes.temperature }}'
    average_up_temp:
      friendly_name: 'Average Upstairs Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {{ ((float(states.sensor.upstairs_hallway_temperature.state) + float(states.climate.upstairs.attributes.current_temperature) + float(states.sensor.hudsons_room_temperature.state) + float(states.sensor.wesleys_room_temperature.state)) / 4) | round(0) }}

    average_down_temp:
      friendly_name: 'Average Downstairs Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {{ ((float(states.sensor.kitchen_temperature.state) + float(states.sensor.master_bedroom_temperature.state) + float(states.climate.downstairs.attributes.current_temperature)) / 3) | round(0) }}

    average_home_temp:
      friendly_name: 'Average Home Temperature'
      unit_of_measurement: '°F'
      value_template: >-
        {{ ((float(states.sensor.upstairs_hallway_temperature.state) + float(states.climate.upstairs.attributes.current_temperature) + float(states.sensor.kitchen_temperature.state) + float(states.sensor.master_bedroom_temperature.state) + float(states.climate.downstairs.attributes.current_temperature) + float(states.sensor.hudsons_room_temperature.state) + float(states.sensor.wesleys_room_temperature.state)) / 7) | round(0) }}

    average_up_humid:
      friendly_name: 'Average Upstairs Humidity'
      unit_of_measurement: '%'
      value_template: >-
        {{ ((float(states.sensor.upstairs_hallway_humidity.state) + float(states.sensor.hudsons_room_humidity.state) + float(states.sensor.wesleys_room_humidity.state)) / 3) | round(0) }}

    average_down_humid:
      friendly_name: 'Average Downstairs Humdity'
      unit_of_measurement: '°%'
      value_template: >-
        {{ ((float(states.sensor.kitchen_humidity.state) + float(states.sensor.master_bedroom_humidity.state)) / 2) | round(0) }}

    average_home_humid:
      friendly_name: 'Average Home Humidity'
      unit_of_measurement: '°%'
      value_template: >-
        {{ ((float(states.sensor.upstairs_hallway_humidity.state) + float(states.sensor.kitchen_humidity.state) + float(states.sensor.master_bedroom_humidity.state) + float(states.sensor.hudsons_room_humidity.state) + float(states.sensor.wesleys_room_humidity.state)) / 5) | round(0) }}

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: rest
  scan_interval: 86400
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'

- platform: command_line
  name: "Uptime"
  command: echo "$(($(date +%s) - $(date -d "$(head -n1 /opt/jarvis/home-assistant.log | cut -d' ' -f-2)" +%s)))"
  scan_interval: 720
  value_template: >-
    {% set uptime = value | int %}
    {% set seconds = uptime % 60 %}
    {% set minutes = ((uptime % 3600) / 60) | int %}
    {% set hours = ((uptime % 86400) / 3600) | int %}
    {% set days = (uptime / 86400) | int %}
    {%- if days > 0 -%}
      {%- if days == 1 -%}
        1 day
      {%- else -%}
        {{ days }} days
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {{ '%02d' % hours }}:{{ '%02d' % minutes }}

- platform: command_line
  name: System volume
  command: /opt/jarvis/scripts/getvolume.sh
  unit_of_measurement: percent

- platform: command_line
  name: Day of Week
  command: /opt/jarvis/scripts/getdayofweek.sh

- platform: command_line
  name: Month
  command: /opt/jarvis/scripts/getmonth.sh

- platform: command_line
  name: Day
  command: /opt/jarvis/scripts/getday.sh

- platform: command_line
  name: Internet Status
  command: /opt/jarvis/scripts/internetstatus.sh

- platform: random
  name: random_outside_lights
  minimum: 1
  maximum: 6

- platform: random
  name: random_2
  minimum: 1
  maximum: 2

- platform: random
  name: random_3
  minimum: 1
  maximum: 3

- platform: random
  name: random_4
  minimum: 1
  maximum: 4

- platform: random
  name: random_5
  minimum: 1
  maximum: 5

- platform: random
  name: random_10
  minimum: 1
  maximum: 10

- platform: random
  name: random_rules
  minimum: 1
  maximum: 50
